<?php

// Plugin related constants
define( 'PLUGIN_NAME_APPSTV_CRM_PRODUCTS', "appstv_crm_products" );

define( 'APPSTV_CRM_PRODUCTS_DATA_DIR_PATH', PLUGIN_NAME_APPSTV_CRM_PRODUCTS . FILE_SEPARATOR . "data"  );
define( 'APPSTV_CRM_PRODUCTS_PRODUCT_IMAGES_DIR_NAME', "product-images" );
define( 'APPSTV_CRM_PRODUCTS_PRODUCT_IMAGES_DIR_PATH', APPSTV_CRM_PRODUCTS_DATA_DIR_PATH . FILE_SEPARATOR . APPSTV_CRM_PRODUCTS_PRODUCT_IMAGES_DIR_NAME );

?>